name: app_ia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  get_it: ^8.0.3
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  uuid: ^4.5.1
  lottie: ^3.3.1
  audio_streamer: ^4.2.2
  record: ^6.0.0
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/futuristic_face.png
    - .env
